2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_setup.py:_flush():68] Configure stats pid to 10280
2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-02 13:39:58,321 INFO    MainThread:10280 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_133958-1y8li5nk\logs\debug.log
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_133958-1y8li5nk\logs\debug-internal.log
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002B580E9BA30>
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:init():532] calling init triggers
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:init():588] starting backend
2023-03-02 13:39:58,322 INFO    MainThread:10280 [wandb_init.py:init():592] setting up manager
2023-03-02 13:39:58,325 INFO    MainThread:10280 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-02 13:39:58,329 INFO    MainThread:10280 [wandb_init.py:init():599] backend started and connected
2023-03-02 13:39:58,341 INFO    MainThread:10280 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-02 13:39:58,343 INFO    MainThread:10280 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-02 13:39:58,343 INFO    MainThread:10280 [wandb_init.py:init():687] updated telemetry
2023-03-02 13:39:58,407 INFO    MainThread:10280 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-02 13:39:59,192 INFO    MainThread:10280 [wandb_run.py:_on_init():2134] communicating current version
2023-03-02 13:39:59,255 INFO    MainThread:10280 [wandb_run.py:_on_init():2143] got version response 
2023-03-02 13:39:59,255 INFO    MainThread:10280 [wandb_init.py:init():775] starting run threads in backend
2023-03-02 13:40:12,486 INFO    MainThread:10280 [wandb_run.py:_console_start():2114] atexit reg
2023-03-02 13:40:12,486 INFO    MainThread:10280 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-02 13:40:12,487 INFO    MainThread:10280 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-02 13:40:12,487 INFO    MainThread:10280 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-02 13:40:12,488 INFO    MainThread:10280 [wandb_init.py:init():817] run started, returning control to user process
2023-03-02 13:40:13,235 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:40:13,235 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:40:48,260 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:40:49,248 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:40:49,248 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:40:58,888 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:40:59,102 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:40:59,102 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:40:59,152 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:00,626 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:00,626 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:00,654 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,132 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,133 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,143 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,153 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,153 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,166 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,169 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,169 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,186 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,196 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,196 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,202 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,202 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,202 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,220 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,220 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,220 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,235 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,251 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,251 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:01,715 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:01,721 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:01,721 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:02,192 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:02,198 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:02,198 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:02,609 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:02,612 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:02,612 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:03,401 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:03,403 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:03,403 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:04,186 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:04,202 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:04,202 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:05,764 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:05,786 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:41:05,786 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:41:17,657 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:41:19,671 INFO    MainThread:10280 [pyagent.py:run():314] Starting sweep agent: entity=None, project=None, count=100
2023-03-02 13:41:27,891 WARNING MsgRouterThr:10280 [router.py:message_loop():77] message_loop has been closed
2023-03-02 13:48:46,760 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:48:46,760 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:50:20,308 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:50:20,334 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:50:20,338 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:50:44,992 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:50:45,300 ERROR   MainThread:10280 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:50:45,300 ERROR   MainThread:10280 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:50:45,361 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:50:45,361 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:51:04,614 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:51:04,949 ERROR   MainThread:10280 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:51:04,949 ERROR   MainThread:10280 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:51:04,998 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:51:04,998 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:51:19,684 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:51:19,710 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:51:19,710 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:51:22,245 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:51:22,579 ERROR   MainThread:10280 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:51:22,579 ERROR   MainThread:10280 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:51:22,620 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:51:22,620 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:52:21,943 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:52:21,969 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:52:21,969 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:52:26,168 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:52:26,492 ERROR   MainThread:10280 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:52:26,492 ERROR   MainThread:10280 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:52:26,531 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:52:26,531 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
2023-03-02 13:52:46,800 INFO    MainThread:10280 [wandb_init.py:_resume_backend():408] resuming backend
2023-03-02 13:52:47,302 ERROR   MainThread:10280 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-02 13:52:47,302 ERROR   MainThread:10280 [internal_api.py:execute():246] {"errors":[{"message":"entity not found during upsertSweep","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2023-03-02 13:52:47,356 INFO    MainThread:10280 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-02 13:52:47,357 INFO    MainThread:10280 [wandb_init.py:_pause_backend():403] pausing backend
