2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_setup.py:_flush():68] Configure stats pid to 22164
2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\.config\wandb\settings
2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_setup.py:_flush():68] Loading settings from C:\Users\anant\CS6910\Assignment 1\wandb\settings
2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-02 12:58:43,986 INFO    MainThread:22164 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_125843-v347ty2t\logs\debug.log
2023-03-02 12:58:43,991 INFO    MainThread:22164 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\anant\CS6910\Assignment 1\wandb\run-20230302_125843-v347ty2t\logs\debug-internal.log
2023-03-02 12:58:43,991 INFO    MainThread:22164 [wandb_init.py:init():532] calling init triggers
2023-03-02 12:58:43,991 INFO    MainThread:22164 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2023-03-02 12:58:43,991 INFO    MainThread:22164 [wandb_init.py:init():588] starting backend
2023-03-02 12:58:43,991 INFO    MainThread:22164 [wandb_init.py:init():592] setting up manager
2023-03-02 12:58:43,991 INFO    MainThread:22164 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-02 12:58:44,007 INFO    MainThread:22164 [wandb_init.py:init():599] backend started and connected
2023-03-02 12:58:44,064 INFO    MainThread:22164 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-02 12:58:44,064 INFO    MainThread:22164 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-02 12:58:44,064 INFO    MainThread:22164 [wandb_init.py:init():687] updated telemetry
2023-03-02 12:58:44,938 INFO    MainThread:22164 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-02 12:59:45,490 ERROR   MainThread:22164 [wandb_init.py:init():741] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-03-02 12:59:45,506 ERROR   MainThread:22164 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\anant\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 759, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
